import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docsSidebar: [
    // Introduction
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro/what-is-evalify',
        'intro/core-features',
        'intro/system-architecture',
        'intro/terminology',
      ],
    },

    // Setup
    {
      type: 'category',
      label: 'Setup & Access',
      items: [
        'setup/login',
      ],
    },

    // Admin Section
    {
      type: 'category',
      label: 'Admin Guide',
      items: [
        'admin/overview',
        {
          type: 'category',
          label: 'Configurations',
          items: [
            'admin/config/user-creation',
            'admin/config/course-creation',
            'admin/config/batch-creation',
            'admin/config/semester-creation',
            'admin/config/lab-creation',
            'admin/config/department-creation',
          ],
        },
        'admin/logs-and-monitoring',
        'admin/permissions-and-access',
      ],
    },

    // Faculty & Manager
    {
      type: 'category',
      label: 'Faculty & Manager Guide',
      items: [
        'faculty/overview',
        'faculty/view-course',
        {
          type: 'category',
          label: 'Quiz Management',
          items: [
            'faculty/quiz/create-quiz',
            'faculty/quiz/manage-questions',
            'faculty/quiz/assign-quiz',
            'faculty/quiz/add-questions-from-bank'
          ],
        },
        {
          type: 'category',
          label: 'Question Bank Management',
          items: [
            'faculty/bank/bank-overview',
          ],
        },
        {
          type: 'category',
          label: 'Questions Types',
          items: [
            'faculty/questions/types/mcq',
            'faculty/questions/types/true-or-false',
            'faculty/questions/types/fill-in-blanks',
            'faculty/questions/types/descriptive',
            'faculty/questions/types/match-the-following',
            'faculty/questions/types/coding',
            'faculty/questions/types/file-upload',
          ],
        },
        'faculty/evaluation-and-grading',
        'faculty/publish-results',
        'faculty/reporting-and-analytics',
      ],
    },

    // Student
    {
      type: 'category',
      label: 'Student Guide',
      items: [
        'student/overview',
        'student/view-course',
        'student/view-quizzes',
        'student/take-quiz',
        'student/view-results',
      ],
    },

    // System wide
    {
      type: 'category',
      label: 'Platform Features',
      items: [
        'platform/notifications',
        'platform/profile-management',
        'platform/security',
        'platform/audit-log',
      ],
    },

    // FAQs
    {
      type: 'category',
      label: 'Help & Troubleshooting',
      items: [
        'help/common-issues',
        'help/student-issues',
        'help/faculty-issues',
        'help/admin-issues',
        'help/report-issue',
      ],
    },
  ],
};

export default sidebars;

